# Generated by Django 2.2.17 on 2021-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.TextField()),
                ('gross_area', models.TextField()),
                ('rent', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('expected_tenants', models.IntegerField()),
                ('created', models.DateField()),
                ('updated', models.DateField()),
            ],
        ),
    ]
