# Generated by Django 2.2.17 on 2021-05-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='title',
            field=models.CharField(default='residence', max_length=200),
            preserve_default=False,
        ),
    ]
