# Generated by Django 2.2.17 on 2021-05-07 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0002_residence_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='owner',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residence',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
