# Generated by Django 2.2.17 on 2021-05-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210507_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='owner',
        ),
    ]
