# Generated by Django 2.2.17 on 2021-05-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_residence_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='owner',
        ),
    ]
